-- ============================================================
-- NEWS PLATFORM — DATABASE SCHEMA (Final)
-- Version: v7
-- Stack: Supabase PostgreSQL
-- ============================================================


-- ============================================================
-- EXTENSIONS
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "unaccent";


-- ============================================================
-- TABLES
-- ============================================================

-- ------------------------------------------------------------
-- SITE SETTINGS (singleton)
-- ------------------------------------------------------------

CREATE TABLE "site_settings" (
  "id"         integer PRIMARY KEY DEFAULT 1,
  "brand"      jsonb NOT NULL,
  "footer"     jsonb NOT NULL,
  "updated_at" timestamptz DEFAULT now(),
  CONSTRAINT "check_single_row" CHECK ("id" = 1)
);


-- ------------------------------------------------------------
-- PROFILES
-- ------------------------------------------------------------

CREATE TABLE "profiles" (
  "id"           uuid PRIMARY KEY,
  "username"     varchar(50)  UNIQUE NOT NULL,
  "display_name" varchar(100),
  "avatar_key"   text,
  "role"         varchar(20)  NOT NULL DEFAULT 'admin',
  "created_at"   timestamptz DEFAULT now(),
  "updated_at"   timestamptz DEFAULT now()
);

ALTER TABLE "profiles"
ADD CONSTRAINT "profiles_role_check"
CHECK ("role" IN ('admin', 'editor'));


-- ------------------------------------------------------------
-- CATEGORIES
-- ------------------------------------------------------------

CREATE TABLE "categories" (
  "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"        varchar(100) NOT NULL,
  "slug"        varchar(100) NOT NULL,
  "priority"    integer DEFAULT 0,
  "status"      varchar(20)  DEFAULT 'active',
  "created_at"  timestamptz DEFAULT now(),
  "updated_at"  timestamptz DEFAULT now(),
  "deleted_at"  timestamptz
);

ALTER TABLE "categories"
ADD CONSTRAINT "categories_status_check"
CHECK ("status" IN ('active', 'inactive'));

-- Unique slug/name chỉ áp dụng cho row chưa bị soft delete
CREATE UNIQUE INDEX "categories_slug_unique_idx"
ON "categories" ("slug")
WHERE ("deleted_at" IS NULL);

CREATE UNIQUE INDEX "categories_name_unique_idx"
ON "categories" ("name")
WHERE ("deleted_at" IS NULL);


-- ------------------------------------------------------------
-- ARTICLES
-- ------------------------------------------------------------

CREATE TABLE "articles" (
  "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title"           varchar(255) NOT NULL,
  "slug"            varchar(255) NOT NULL,
  "summary"         text,
  "thumbnail_key"   text,
  "content"         jsonb        NOT NULL,
  "category_id"     bigint,
  "author_id"       uuid,
  "views"           bigint       NOT NULL DEFAULT 0,   -- tổng aggregate, flush từ Redis
  "status"          varchar(20)  NOT NULL DEFAULT 'draft',
  "featured"        boolean      DEFAULT false,
  "seo_title"       varchar(255),
  "seo_description" text,
  "search_vector"   tsvector,                          -- PostgreSQL Full-Text Search
  "created_at"      timestamptz  DEFAULT now(),
  "updated_at"      timestamptz  DEFAULT now(),
  "published_at"    timestamptz,
  "deleted_at"      timestamptz
);

ALTER TABLE "articles"
ADD CONSTRAINT "articles_status_check"
CHECK ("status" IN ('draft', 'published'));

-- Unique slug chỉ áp dụng cho row chưa bị soft delete
CREATE UNIQUE INDEX "articles_slug_unique_idx"
ON "articles" ("slug")
WHERE ("deleted_at" IS NULL);

-- Query indexes
CREATE INDEX "articles_category_id_idx"  ON "articles" ("category_id");
CREATE INDEX "articles_author_id_idx"    ON "articles" ("author_id");
CREATE INDEX "articles_status_idx"       ON "articles" ("status");
CREATE INDEX "articles_published_at_idx" ON "articles" ("published_at");
CREATE INDEX "articles_deleted_at_idx"   ON "articles" ("deleted_at");
CREATE INDEX "articles_featured_idx"     ON "articles" ("featured") WHERE ("featured" = true AND "deleted_at" IS NULL);

-- Full-Text Search index (GIN)
CREATE INDEX "articles_search_vector_idx"
ON "articles" USING GIN ("search_vector");


-- ------------------------------------------------------------
-- ADS
-- ------------------------------------------------------------

CREATE TABLE "ads" (
  "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"       varchar(100) NOT NULL,
  "type"       varchar(30)  NOT NULL,
  "position"   varchar(50)  NOT NULL,
  "media_key"  text,
  "html_code"  text,
  "target_url" text,
  "priority"   integer      DEFAULT 0,
  "status"     varchar(20)  DEFAULT 'active',
  "starts_at"  timestamptz,
  "ends_at"    timestamptz,
  "created_at" timestamptz  DEFAULT now(),
  "updated_at" timestamptz  DEFAULT now(),
  "deleted_at" timestamptz
);

ALTER TABLE "ads"
ADD CONSTRAINT "ads_status_check"
CHECK ("status" IN ('active', 'inactive'));

ALTER TABLE "ads"
ADD CONSTRAINT "ads_type_check"
CHECK ("type" IN ('image', 'html', 'video'));

CREATE INDEX "ads_position_status_idx" ON "ads" ("position", "status");
CREATE INDEX "ads_deleted_at_idx"      ON "ads" ("deleted_at");
CREATE INDEX "ads_starts_ends_idx"     ON "ads" ("starts_at", "ends_at");


-- ============================================================
-- FOREIGN KEYS
-- ============================================================

ALTER TABLE "articles"
ADD CONSTRAINT "articles_category_id_fkey"
FOREIGN KEY ("category_id")
REFERENCES "categories" ("id")
ON DELETE SET NULL
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "articles"
ADD CONSTRAINT "articles_author_id_fkey"
FOREIGN KEY ("author_id")
REFERENCES "profiles" ("id")
DEFERRABLE INITIALLY IMMEDIATE;


-- ============================================================
-- ANALYTICS / REPORTING
-- ============================================================

-- ------------------------------------------------------------
-- ARTICLE STATS DAILY
-- ------------------------------------------------------------

CREATE TABLE "article_stats_daily" (
  "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "article_id"   bigint NOT NULL,
  "date"         date   NOT NULL,
  "views"        bigint NOT NULL DEFAULT 0,
  -- unique_views: chỉ populate nếu có fingerprint/cookie tracking
  -- để 0 nếu chưa implement, tránh misleading trong dashboard
  "unique_views" bigint NOT NULL DEFAULT 0,
  "created_at"   timestamptz DEFAULT now(),
  "updated_at"   timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX "article_stats_daily_article_date_uidx"
ON "article_stats_daily" ("article_id", "date");

CREATE INDEX "article_stats_daily_date_idx"
ON "article_stats_daily" ("date");

-- Index cho Trending query (SUM views 7 ngày gần nhất)
CREATE INDEX "article_stats_daily_trending_idx"
ON "article_stats_daily" ("date", "article_id", "views");

ALTER TABLE "article_stats_daily"
ADD CONSTRAINT "article_stats_daily_article_id_fkey"
FOREIGN KEY ("article_id")
REFERENCES "articles" ("id")
ON DELETE CASCADE;


-- ------------------------------------------------------------
-- PAGE STATS DAILY (tổng site traffic)
-- ------------------------------------------------------------

CREATE TABLE "page_stats_daily" (
  "date"            date PRIMARY KEY,
  "page_views"      bigint NOT NULL DEFAULT 0,
  "unique_visitors" bigint NOT NULL DEFAULT 0,
  "sessions"        bigint NOT NULL DEFAULT 0,
  "created_at"      timestamptz DEFAULT now(),
  "updated_at"      timestamptz DEFAULT now()
);


-- ------------------------------------------------------------
-- AD STATS DAILY
-- ------------------------------------------------------------

CREATE TABLE "ad_stats_daily" (
  "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ad_id"       bigint NOT NULL,
  "date"        date   NOT NULL,
  "impressions" bigint NOT NULL DEFAULT 0,
  "clicks"      bigint NOT NULL DEFAULT 0,
  "created_at"  timestamptz DEFAULT now(),
  "updated_at"  timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX "ad_stats_daily_ad_date_uidx"
ON "ad_stats_daily" ("ad_id", "date");

CREATE INDEX "ad_stats_daily_date_idx"
ON "ad_stats_daily" ("date");

ALTER TABLE "ad_stats_daily"
ADD CONSTRAINT "ad_stats_daily_ad_id_fkey"
FOREIGN KEY ("ad_id")
REFERENCES "ads" ("id")
ON DELETE CASCADE;


-- ============================================================
-- SEO REDIRECTS
-- ============================================================

CREATE TABLE "redirects" (
  "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "from_path"   text    NOT NULL,
  "to_path"     text    NOT NULL,
  "status_code" integer NOT NULL DEFAULT 301,
  "created_at"  timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX "redirects_from_path_uidx"
ON "redirects" ("from_path");

ALTER TABLE "redirects"
ADD CONSTRAINT "redirects_status_code_check"
CHECK ("status_code" IN (301, 302, 307, 308));


-- ============================================================
-- FULL-TEXT SEARCH — TRIGGER
-- ============================================================

-- Function cập nhật search_vector khi article được insert/update
-- Dùng 'simple' dictionary để support tiếng Việt (không bị lỗi stemming)
-- unaccent giúp tìm kiếm không phân biệt dấu

CREATE OR REPLACE FUNCTION articles_search_vector_update()
RETURNS trigger AS $$
BEGIN
  NEW.search_vector :=
    setweight(to_tsvector('simple', unaccent(coalesce(NEW.title, ''))),   'A') ||
    setweight(to_tsvector('simple', unaccent(coalesce(NEW.summary, ''))), 'B');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "articles_search_vector_trigger"
BEFORE INSERT OR UPDATE ON "articles"
FOR EACH ROW EXECUTE FUNCTION articles_search_vector_update();


-- ============================================================
-- SERVER-SIDE AGGREGATION FUNCTIONS
-- ============================================================

-- Trending articles: aggregates views from article_stats_daily for the last N days
-- Leverages the article_stats_daily_trending_idx (date, article_id, views)
CREATE OR REPLACE FUNCTION get_trending_articles(p_limit integer, p_days integer)
RETURNS TABLE(article_id bigint, total_views bigint)
LANGUAGE plpgsql STABLE
AS $$
BEGIN
  RETURN QUERY
  SELECT asd.article_id, SUM(asd.views)::bigint AS total_views
  FROM article_stats_daily asd
  WHERE asd.date >= (CURRENT_DATE - p_days)
  GROUP BY asd.article_id
  ORDER BY total_views DESC
  LIMIT p_limit;
END;
$$;

-- Top ads: aggregates impressions from ad_stats_daily for the last N days
CREATE OR REPLACE FUNCTION get_top_ads(p_limit integer, p_days integer)
RETURNS TABLE(ad_id bigint, total_impressions bigint)
LANGUAGE plpgsql STABLE
AS $$
BEGIN
  RETURN QUERY
  SELECT asd.ad_id, SUM(asd.impressions)::bigint AS total_impressions
  FROM ad_stats_daily asd
  WHERE asd.date >= (CURRENT_DATE - p_days)
  GROUP BY asd.ad_id
  ORDER BY total_impressions DESC
  LIMIT p_limit;
END;
$$;


-- ------------------------------------------------------------
-- DASHBOARD OPTIMIZATION RPCs (added in v7)
-- Pre-computes ALL standard timeframes in ONE database call.
-- Replaces old JS-side aggregation that fetched all rows.
-- ------------------------------------------------------------

-- 1. Pre-computes all standard timeframes (today, week, month, year)
--    in a single call. Cache key is shared across all time filters,
--    so switching tabs on the client is instant.
CREATE OR REPLACE FUNCTION get_dashboard_all_timeframes()
RETURNS jsonb
LANGUAGE plpgsql STABLE
AS $$
DECLARE
  today date := (NOW() AT TIME ZONE 'UTC')::date;
  result jsonb;
BEGIN
  WITH 
    total_counts AS (
      SELECT
        (SELECT COUNT(*)::int FROM articles WHERE deleted_at IS NULL) AS total_articles,
        (SELECT COUNT(*)::int FROM categories WHERE deleted_at IS NULL) AS total_categories,
        (SELECT COUNT(*)::int FROM ads WHERE deleted_at IS NULL) AS total_ads
    ),
    article_views AS (
      SELECT
        COALESCE(SUM(views) FILTER (WHERE date = today), 0)::bigint AS today_views,
        COALESCE(SUM(views) FILTER (WHERE date = today - 1), 0)::bigint AS yesterday_views,
        COALESCE(SUM(views) FILTER (WHERE date >= today - 6 AND date <= today), 0)::bigint AS week_views,
        COALESCE(SUM(views) FILTER (WHERE date >= today - 13 AND date <= today - 7), 0)::bigint AS prev_week_views,
        COALESCE(SUM(views) FILTER (WHERE date >= today - 29 AND date <= today), 0)::bigint AS month_views,
        COALESCE(SUM(views) FILTER (WHERE date >= today - 59 AND date <= today - 30), 0)::bigint AS prev_month_views,
        COALESCE(SUM(views) FILTER (WHERE date >= date_trunc('year', today)::date AND date <= today), 0)::bigint AS year_views,
        COALESCE(SUM(views) FILTER (WHERE date >= (date_trunc('year', today) - interval '1 year')::date AND date < date_trunc('year', today)::date), 0)::bigint AS prev_year_views
      FROM article_stats_daily
      WHERE date >= today - 365
    ),
    ad_clicks AS (
      SELECT
        COALESCE(SUM(clicks) FILTER (WHERE date = today), 0)::bigint AS today_clicks,
        COALESCE(SUM(clicks) FILTER (WHERE date = today - 1), 0)::bigint AS yesterday_clicks,
        COALESCE(SUM(clicks) FILTER (WHERE date >= today - 6 AND date <= today), 0)::bigint AS week_clicks,
        COALESCE(SUM(clicks) FILTER (WHERE date >= today - 13 AND date <= today - 7), 0)::bigint AS prev_week_clicks,
        COALESCE(SUM(clicks) FILTER (WHERE date >= today - 29 AND date <= today), 0)::bigint AS month_clicks,
        COALESCE(SUM(clicks) FILTER (WHERE date >= today - 59 AND date <= today - 30), 0)::bigint AS prev_month_clicks,
        COALESCE(SUM(clicks) FILTER (WHERE date >= date_trunc('year', today)::date AND date <= today), 0)::bigint AS year_clicks,
        COALESCE(SUM(clicks) FILTER (WHERE date >= (date_trunc('year', today) - interval '1 year')::date AND date < date_trunc('year', today)::date), 0)::bigint AS prev_year_clicks
      FROM ad_stats_daily
      WHERE date >= today - 365
    ),
    period_counts AS (
      SELECT
        (SELECT COUNT(*)::int FROM articles WHERE deleted_at IS NULL AND created_at >= (today - 29)::timestamptz) AS month_articles,
        (SELECT COUNT(*)::int FROM articles WHERE deleted_at IS NULL AND created_at >= (today - 59)::timestamptz AND created_at < (today - 29)::timestamptz) AS prev_month_articles,
        (SELECT COUNT(*)::int FROM articles WHERE deleted_at IS NULL AND created_at >= date_trunc('year', today)::timestamptz) AS year_articles,
        (SELECT COUNT(*)::int FROM articles WHERE deleted_at IS NULL AND created_at >= (date_trunc('year', today) - interval '1 year')::timestamptz AND created_at < date_trunc('year', today)::timestamptz) AS prev_year_articles
    )
  SELECT jsonb_build_object(
    'totalArticles', (SELECT total_articles FROM total_counts),
    'totalCategories', (SELECT total_categories FROM total_counts),
    'totalAds', (SELECT total_ads FROM total_counts),
    'todayViews', (SELECT today_views FROM article_views),
    'yesterdayViews', (SELECT yesterday_views FROM article_views),
    'todayClicks', (SELECT today_clicks FROM ad_clicks),
    'yesterdayClicks', (SELECT yesterday_clicks FROM ad_clicks),
    'weekViews', (SELECT week_views FROM article_views),
    'prevWeekViews', (SELECT prev_week_views FROM article_views),
    'weekClicks', (SELECT week_clicks FROM ad_clicks),
    'prevWeekClicks', (SELECT prev_week_clicks FROM ad_clicks),
    'monthViews', (SELECT month_views FROM article_views),
    'prevMonthViews', (SELECT prev_month_views FROM article_views),
    'monthClicks', (SELECT month_clicks FROM ad_clicks),
    'prevMonthClicks', (SELECT prev_month_clicks FROM ad_clicks),
    'yearViews', (SELECT year_views FROM article_views),
    'prevYearViews', (SELECT prev_year_views FROM article_views),
    'yearClicks', (SELECT year_clicks FROM ad_clicks),
    'prevYearClicks', (SELECT prev_year_clicks FROM ad_clicks),
    'totalViews', (SELECT year_views + prev_year_views FROM article_views),
    'totalClicks', (SELECT year_clicks + prev_year_clicks FROM ad_clicks),
    'periodArticles', (SELECT month_articles FROM period_counts),
    'prevPeriodArticles', (SELECT prev_month_articles FROM period_counts)
  ) INTO result;

  RETURN result;
END;
$$;


-- 2. Top N articles by views for a given date range (server-side aggregation)
CREATE OR REPLACE FUNCTION get_dashboard_top_articles_range(
  p_start_date date,
  p_end_date date,
  p_limit integer DEFAULT 5
)
RETURNS jsonb
LANGUAGE plpgsql STABLE
AS $$
DECLARE
  result jsonb;
BEGIN
  SELECT jsonb_agg(sub) INTO result FROM (
    SELECT a.id, a.title, COALESCE(c.name, 'Tin tức') AS category, ranked.total_views AS views
    FROM (
      SELECT asd.article_id, SUM(asd.views)::bigint AS total_views
      FROM article_stats_daily asd
      WHERE asd.date >= p_start_date AND asd.date <= p_end_date
      GROUP BY asd.article_id
      ORDER BY total_views DESC
      LIMIT p_limit
    ) ranked
    JOIN articles a ON a.id = ranked.article_id
    LEFT JOIN categories c ON c.id = a.category_id
    WHERE a.status = 'published' AND a.deleted_at IS NULL
  ) sub;

  RETURN COALESCE(result, '[]'::jsonb);
END;
$$;


-- 3. Top N ads by impressions for a given date range (server-side aggregation)
CREATE OR REPLACE FUNCTION get_dashboard_top_ads_range(
  p_start_date date,
  p_end_date date,
  p_limit integer DEFAULT 5
)
RETURNS jsonb
LANGUAGE plpgsql STABLE
AS $$
DECLARE
  result jsonb;
BEGIN
  SELECT jsonb_agg(sub) INTO result FROM (
    SELECT a.*, ranked.total_impressions AS impressions_7d
    FROM (
      SELECT asd.ad_id, SUM(asd.impressions)::bigint AS total_impressions
      FROM ad_stats_daily asd
      WHERE asd.date >= p_start_date AND asd.date <= p_end_date
      GROUP BY asd.ad_id
      ORDER BY total_impressions DESC
      LIMIT p_limit
    ) ranked
    JOIN ads a ON a.id = ranked.ad_id
    WHERE a.deleted_at IS NULL
  ) sub;

  RETURN COALESCE(result, '[]'::jsonb);
END;
$$;


-- 4. Custom date-range stats (day / month / year filter on admin dashboard)
CREATE OR REPLACE FUNCTION get_dashboard_stats_range(
  p_start_date date,
  p_end_date date,
  p_prev_start_date date,
  p_prev_end_date date
)
RETURNS jsonb
LANGUAGE plpgsql STABLE
AS $$
DECLARE
  result jsonb;
BEGIN
  WITH
    total_counts AS (
      SELECT
        (SELECT COUNT(*)::int FROM articles WHERE deleted_at IS NULL) AS total_articles,
        (SELECT COUNT(*)::int FROM categories WHERE deleted_at IS NULL) AS total_categories,
        (SELECT COUNT(*)::int FROM ads WHERE deleted_at IS NULL) AS total_ads
    ),
    period_views AS (
      SELECT
        COALESCE(SUM(views) FILTER (WHERE date >= p_start_date AND date <= p_end_date), 0)::bigint AS views,
        COALESCE(SUM(views) FILTER (WHERE date >= p_prev_start_date AND date <= p_prev_end_date), 0)::bigint AS prev_views
      FROM article_stats_daily
      WHERE date >= LEAST(p_start_date, p_prev_start_date)
        AND date <= GREATEST(p_end_date, p_prev_end_date)
    ),
    period_clicks AS (
      SELECT
        COALESCE(SUM(clicks) FILTER (WHERE date >= p_start_date AND date <= p_end_date), 0)::bigint AS clicks,
        COALESCE(SUM(clicks) FILTER (WHERE date >= p_prev_start_date AND date <= p_prev_end_date), 0)::bigint AS prev_clicks
      FROM ad_stats_daily
      WHERE date >= LEAST(p_start_date, p_prev_start_date)
        AND date <= GREATEST(p_end_date, p_prev_end_date)
    ),
    period_articles AS (
      SELECT
        (SELECT COUNT(*)::int FROM articles
          WHERE deleted_at IS NULL
            AND created_at >= p_start_date::timestamptz
            AND created_at < (p_end_date + 1)::timestamptz) AS period_articles,
        (SELECT COUNT(*)::int FROM articles
          WHERE deleted_at IS NULL
            AND created_at >= p_prev_start_date::timestamptz
            AND created_at < (p_prev_end_date + 1)::timestamptz) AS prev_period_articles
    )
  SELECT jsonb_build_object(
    'totalArticles', (SELECT total_articles FROM total_counts),
    'totalCategories', (SELECT total_categories FROM total_counts),
    'totalAds', (SELECT total_ads FROM total_counts),
    'todayViews', (SELECT views FROM period_views),
    'yesterdayViews', (SELECT prev_views FROM period_views),
    'todayClicks', (SELECT clicks FROM period_clicks),
    'yesterdayClicks', (SELECT prev_clicks FROM period_clicks),
    'weekViews', (SELECT views FROM period_views),
    'prevWeekViews', (SELECT prev_views FROM period_views),
    'weekClicks', (SELECT clicks FROM period_clicks),
    'prevWeekClicks', (SELECT prev_clicks FROM period_clicks),
    'monthViews', (SELECT views FROM period_views),
    'prevMonthViews', (SELECT prev_views FROM period_views),
    'monthClicks', (SELECT clicks FROM period_clicks),
    'prevMonthClicks', (SELECT prev_clicks FROM period_clicks),
    'yearViews', (SELECT views FROM period_views),
    'prevYearViews', (SELECT prev_views FROM period_views),
    'yearClicks', (SELECT clicks FROM period_clicks),
    'prevYearClicks', (SELECT prev_clicks FROM period_clicks),
    'totalViews', (SELECT views FROM period_views),
    'totalClicks', (SELECT clicks FROM period_clicks),
    'periodArticles', (SELECT period_articles FROM period_articles),
    'prevPeriodArticles', (SELECT prev_period_articles FROM period_articles)
  ) INTO result;

  RETURN result;
END;
$$;


-- ============================================================
-- SEED — SITE SETTINGS (default row)
-- ============================================================

INSERT INTO "site_settings" ("id", "brand", "footer")
VALUES (
  1,
  '{"name": "", "logo_key": "", "favicon_key": ""}',
  '{"copyright": "", "links": []}'
)
ON CONFLICT ("id") DO NOTHING;


-- ============================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================

-- redirects: Middleware dùng anon client → cần policy SELECT public
-- Nếu không có policy này, middleware sẽ không đọc được redirect rules
ALTER TABLE "redirects" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "redirects_public_read"
ON "redirects"
FOR SELECT
USING (true);

-- Chỉ service role mới được INSERT/UPDATE/DELETE
CREATE POLICY "redirects_service_write"
ON "redirects"
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);


-- page_stats_daily: Chỉ service_role write (flush từ cron)
-- SELECT được phép để dashboard có thể đọc
ALTER TABLE "page_stats_daily" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "page_stats_public_read"
ON "page_stats_daily"
FOR SELECT
USING (true);

CREATE POLICY "page_stats_service_write"
ON "page_stats_daily"
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);


-- ============================================================
-- VIEWS (for dashboard & public page optimization)
-- ============================================================

-- Top categories with article count (used by dashboard getTopCategories fallback)
CREATE OR REPLACE VIEW view_top_categories AS
SELECT 
  c.id, 
  c.name, 
  c.slug, 
  c.updated_at,
  COUNT(a.id)::int AS article_count
FROM categories c
LEFT JOIN articles a ON a.category_id = c.id AND a.status = 'published' AND a.deleted_at IS NULL
WHERE c.deleted_at IS NULL
GROUP BY c.id, c.name, c.slug, c.updated_at
ORDER BY article_count DESC;

-- Top ads based on 7-day impressions
CREATE OR REPLACE VIEW view_top_ads_7d AS
SELECT 
  a.id,
  a.name,
  a.type,
  a.position,
  a.media_key,
  a.html_code,
  a.target_url,
  a.priority,
  a.status,
  a.starts_at,
  a.ends_at,
  a.created_at,
  a.updated_at,
  a.deleted_at,
  COALESCE(SUM(s.impressions), 0)::int AS impressions_7d
FROM ads a
LEFT JOIN ad_stats_daily s ON s.ad_id = a.id AND s.date >= (CURRENT_DATE - INTERVAL '7 days')::date
WHERE a.deleted_at IS NULL
GROUP BY a.id;

-- Dashboard metrics (single-query aggregation replacing 20+ individual queries)
CREATE OR REPLACE VIEW view_dashboard_metrics AS
WITH 
  counts AS (
    SELECT
      (SELECT COUNT(*)::int FROM articles WHERE deleted_at IS NULL) AS total_articles,
      (SELECT COUNT(*)::int FROM categories WHERE deleted_at IS NULL) AS total_categories,
      (SELECT COUNT(*)::int FROM ads WHERE deleted_at IS NULL) AS total_ads
  ),
  article_sums AS (
    SELECT
      COALESCE(SUM(views), 0)::bigint AS total_views,
      COALESCE(SUM(CASE WHEN date = (NOW() AT TIME ZONE 'UTC')::date THEN views ELSE 0 END), 0)::bigint AS today_views,
      COALESCE(SUM(CASE WHEN date = (NOW() AT TIME ZONE 'UTC')::date - 1 THEN views ELSE 0 END), 0)::bigint AS yesterday_views,
      COALESCE(SUM(CASE WHEN date >= (NOW() AT TIME ZONE 'UTC')::date - 7 THEN views ELSE 0 END), 0)::bigint AS week_views,
      COALESCE(SUM(CASE WHEN date >= (NOW() AT TIME ZONE 'UTC')::date - 14 AND date < (NOW() AT TIME ZONE 'UTC')::date - 7 THEN views ELSE 0 END), 0)::bigint AS prev_week_views,
      COALESCE(SUM(CASE WHEN date >= (NOW() AT TIME ZONE 'UTC')::date - 30 THEN views ELSE 0 END), 0)::bigint AS month_views,
      COALESCE(SUM(CASE WHEN date >= (NOW() AT TIME ZONE 'UTC')::date - 60 AND date < (NOW() AT TIME ZONE 'UTC')::date - 30 THEN views ELSE 0 END), 0)::bigint AS prev_month_views
    FROM article_stats_daily
  ),
  ad_sums AS (
    SELECT
      COALESCE(SUM(clicks), 0)::bigint AS total_clicks,
      COALESCE(SUM(CASE WHEN date = (NOW() AT TIME ZONE 'UTC')::date THEN clicks ELSE 0 END), 0)::bigint AS today_clicks,
      COALESCE(SUM(CASE WHEN date = (NOW() AT TIME ZONE 'UTC')::date - 1 THEN clicks ELSE 0 END), 0)::bigint AS yesterday_clicks,
      COALESCE(SUM(CASE WHEN date >= (NOW() AT TIME ZONE 'UTC')::date - 7 THEN clicks ELSE 0 END), 0)::bigint AS week_clicks,
      COALESCE(SUM(CASE WHEN date >= (NOW() AT TIME ZONE 'UTC')::date - 14 AND date < (NOW() AT TIME ZONE 'UTC')::date - 7 THEN clicks ELSE 0 END), 0)::bigint AS prev_week_clicks,
      COALESCE(SUM(CASE WHEN date >= (NOW() AT TIME ZONE 'UTC')::date - 30 THEN clicks ELSE 0 END), 0)::bigint AS month_clicks,
      COALESCE(SUM(CASE WHEN date >= (NOW() AT TIME ZONE 'UTC')::date - 60 AND date < (NOW() AT TIME ZONE 'UTC')::date - 30 THEN clicks ELSE 0 END), 0)::bigint AS prev_month_clicks
    FROM ad_stats_daily
  )
SELECT
  c.total_articles,
  c.total_categories,
  c.total_ads,
  v.total_views,
  k.total_clicks,
  v.today_views,
  v.yesterday_views,
  k.today_clicks,
  k.yesterday_clicks,
  v.week_views,
  v.prev_week_views,
  k.week_clicks,
  k.prev_week_clicks,
  v.month_views,
  v.prev_month_views,
  k.month_clicks,
  k.prev_month_clicks
FROM counts c
CROSS JOIN article_sums v
CROSS JOIN ad_sums k;


-- ==============================================
-- PERFORMANCE OPTIMIZATION INDEXES
-- ==============================================

-- 1. Index for articles sorting by created_at and deleted_at filter
CREATE INDEX IF NOT EXISTS "articles_deleted_created_idx" ON "articles" ("deleted_at", "created_at" DESC);

-- 2. Index for sorting by published_at (used in public feed and homepage listings)
CREATE INDEX IF NOT EXISTS "articles_published_at_desc_idx" ON "articles" ("published_at" DESC) WHERE ("status" = 'published' AND "deleted_at" IS NULL);

-- 3. Composite Index for category joins, status, and deletion filters
CREATE INDEX IF NOT EXISTS "articles_category_status_deleted_idx" ON "articles" ("category_id", "status", "deleted_at");

-- 4. Index for sorting ads by priority and active status
CREATE INDEX IF NOT EXISTS "ads_status_deleted_priority_idx" ON "ads" ("status", "priority" DESC) WHERE ("deleted_at" IS NULL);

-- 5. Index for sorting categories by priority
CREATE INDEX IF NOT EXISTS "categories_status_deleted_priority_idx" ON "categories" ("status", "priority" DESC) WHERE ("deleted_at" IS NULL);

-- 6. Partial composite index for category page queries (category_id + status + deleted_at + published_at DESC)
CREATE INDEX IF NOT EXISTS "articles_category_published_idx"
ON "articles" ("category_id", "published_at" DESC)
WHERE ("status" = 'published' AND "deleted_at" IS NULL);

-- 7. Composite index for ads dashboard list queries (deleted_at IS NULL + created_at DESC)
CREATE INDEX IF NOT EXISTS "ads_deleted_created_idx"
ON "ads" ("deleted_at", "created_at" DESC);

-- 8. Composite index for categories dashboard list queries (deleted_at IS NULL + created_at DESC)
CREATE INDEX IF NOT EXISTS "categories_deleted_created_idx"
ON "categories" ("deleted_at", "created_at" DESC);
