-- ============================================================
-- NEWS PLATFORM — DATABASE SCHEMA (Final)
-- Version: v6
-- Stack: Supabase PostgreSQL
-- ============================================================


-- ============================================================
-- EXTENSIONS
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "unaccent";


-- ============================================================
-- TABLES
-- ============================================================

-- ------------------------------------------------------------
-- SITE SETTINGS (singleton)
-- ------------------------------------------------------------

CREATE TABLE "site_settings" (
  "id"         integer PRIMARY KEY DEFAULT 1,
  "brand"      jsonb NOT NULL,
  "footer"     jsonb NOT NULL,
  "updated_at" timestamptz DEFAULT now(),
  CONSTRAINT "check_single_row" CHECK ("id" = 1)
);


-- ------------------------------------------------------------
-- PROFILES
-- ------------------------------------------------------------

CREATE TABLE "profiles" (
  "id"           uuid PRIMARY KEY,
  "username"     varchar(50)  UNIQUE NOT NULL,
  "display_name" varchar(100),
  "avatar_key"   text,
  "role"         varchar(20)  NOT NULL DEFAULT 'admin',
  "created_at"   timestamptz DEFAULT now(),
  "updated_at"   timestamptz DEFAULT now()
);

ALTER TABLE "profiles"
ADD CONSTRAINT "profiles_role_check"
CHECK ("role" IN ('admin', 'editor'));


-- ------------------------------------------------------------
-- CATEGORIES
-- ------------------------------------------------------------

CREATE TABLE "categories" (
  "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"        varchar(100) NOT NULL,
  "slug"        varchar(100) NOT NULL,
  "priority"    integer DEFAULT 0,
  "status"      varchar(20)  DEFAULT 'active',
  "created_at"  timestamptz DEFAULT now(),
  "updated_at"  timestamptz DEFAULT now(),
  "deleted_at"  timestamptz
);

ALTER TABLE "categories"
ADD CONSTRAINT "categories_status_check"
CHECK ("status" IN ('active', 'inactive'));

-- Unique slug/name chỉ áp dụng cho row chưa bị soft delete
CREATE UNIQUE INDEX "categories_slug_unique_idx"
ON "categories" ("slug")
WHERE ("deleted_at" IS NULL);

CREATE UNIQUE INDEX "categories_name_unique_idx"
ON "categories" ("name")
WHERE ("deleted_at" IS NULL);


-- ------------------------------------------------------------
-- ARTICLES
-- ------------------------------------------------------------

CREATE TABLE "articles" (
  "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title"           varchar(255) NOT NULL,
  "slug"            varchar(255) NOT NULL,
  "summary"         text,
  "thumbnail_key"   text,
  "content"         jsonb        NOT NULL,
  "category_id"     bigint,
  "author_id"       uuid,
  "views"           bigint       NOT NULL DEFAULT 0,   -- tổng aggregate, flush từ Redis
  "status"          varchar(20)  NOT NULL DEFAULT 'draft',
  "featured"        boolean      DEFAULT false,
  "seo_title"       varchar(255),
  "seo_description" text,
  "search_vector"   tsvector,                          -- PostgreSQL Full-Text Search
  "created_at"      timestamptz  DEFAULT now(),
  "updated_at"      timestamptz  DEFAULT now(),
  "published_at"    timestamptz,
  "deleted_at"      timestamptz
);

ALTER TABLE "articles"
ADD CONSTRAINT "articles_status_check"
CHECK ("status" IN ('draft', 'published'));

-- Unique slug chỉ áp dụng cho row chưa bị soft delete
CREATE UNIQUE INDEX "articles_slug_unique_idx"
ON "articles" ("slug")
WHERE ("deleted_at" IS NULL);

-- Query indexes
CREATE INDEX "articles_category_id_idx"  ON "articles" ("category_id");
CREATE INDEX "articles_author_id_idx"    ON "articles" ("author_id");
CREATE INDEX "articles_status_idx"       ON "articles" ("status");
CREATE INDEX "articles_published_at_idx" ON "articles" ("published_at");
CREATE INDEX "articles_deleted_at_idx"   ON "articles" ("deleted_at");
CREATE INDEX "articles_featured_idx"     ON "articles" ("featured") WHERE ("featured" = true AND "deleted_at" IS NULL);

-- Full-Text Search index (GIN)
CREATE INDEX "articles_search_vector_idx"
ON "articles" USING GIN ("search_vector");


-- ------------------------------------------------------------
-- ADS
-- ------------------------------------------------------------

CREATE TABLE "ads" (
  "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"       varchar(100) NOT NULL,
  "type"       varchar(30)  NOT NULL,
  "position"   varchar(50)  NOT NULL,
  "media_key"  text,
  "html_code"  text,
  "target_url" text,
  "priority"   integer      DEFAULT 0,
  "status"     varchar(20)  DEFAULT 'active',
  "starts_at"  timestamptz,
  "ends_at"    timestamptz,
  "created_at" timestamptz  DEFAULT now(),
  "updated_at" timestamptz  DEFAULT now(),
  "deleted_at" timestamptz
);

ALTER TABLE "ads"
ADD CONSTRAINT "ads_status_check"
CHECK ("status" IN ('active', 'inactive'));

ALTER TABLE "ads"
ADD CONSTRAINT "ads_type_check"
CHECK ("type" IN ('image', 'html', 'video'));

CREATE INDEX "ads_position_status_idx" ON "ads" ("position", "status");
CREATE INDEX "ads_deleted_at_idx"      ON "ads" ("deleted_at");
CREATE INDEX "ads_starts_ends_idx"     ON "ads" ("starts_at", "ends_at");


-- ============================================================
-- FOREIGN KEYS
-- ============================================================

ALTER TABLE "articles"
ADD CONSTRAINT "articles_category_id_fkey"
FOREIGN KEY ("category_id")
REFERENCES "categories" ("id")
ON DELETE SET NULL
DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "articles"
ADD CONSTRAINT "articles_author_id_fkey"
FOREIGN KEY ("author_id")
REFERENCES "profiles" ("id")
DEFERRABLE INITIALLY IMMEDIATE;


-- ============================================================
-- ANALYTICS / REPORTING
-- ============================================================

-- ------------------------------------------------------------
-- ARTICLE STATS DAILY
-- ------------------------------------------------------------

CREATE TABLE "article_stats_daily" (
  "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "article_id"   bigint NOT NULL,
  "date"         date   NOT NULL,
  "views"        bigint NOT NULL DEFAULT 0,
  -- unique_views: chỉ populate nếu có fingerprint/cookie tracking
  -- để 0 nếu chưa implement, tránh misleading trong dashboard
  "unique_views" bigint NOT NULL DEFAULT 0,
  "created_at"   timestamptz DEFAULT now(),
  "updated_at"   timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX "article_stats_daily_article_date_uidx"
ON "article_stats_daily" ("article_id", "date");

CREATE INDEX "article_stats_daily_date_idx"
ON "article_stats_daily" ("date");

-- Index cho Trending query (SUM views 7 ngày gần nhất)
CREATE INDEX "article_stats_daily_trending_idx"
ON "article_stats_daily" ("date", "article_id", "views");

ALTER TABLE "article_stats_daily"
ADD CONSTRAINT "article_stats_daily_article_id_fkey"
FOREIGN KEY ("article_id")
REFERENCES "articles" ("id")
ON DELETE CASCADE;


-- ------------------------------------------------------------
-- PAGE STATS DAILY (tổng site traffic)
-- ------------------------------------------------------------

CREATE TABLE "page_stats_daily" (
  "date"            date PRIMARY KEY,
  "page_views"      bigint NOT NULL DEFAULT 0,
  "unique_visitors" bigint NOT NULL DEFAULT 0,
  "sessions"        bigint NOT NULL DEFAULT 0,
  "created_at"      timestamptz DEFAULT now(),
  "updated_at"      timestamptz DEFAULT now()
);


-- ------------------------------------------------------------
-- AD STATS DAILY
-- ------------------------------------------------------------

CREATE TABLE "ad_stats_daily" (
  "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ad_id"       bigint NOT NULL,
  "date"        date   NOT NULL,
  "impressions" bigint NOT NULL DEFAULT 0,
  "clicks"      bigint NOT NULL DEFAULT 0,
  "created_at"  timestamptz DEFAULT now(),
  "updated_at"  timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX "ad_stats_daily_ad_date_uidx"
ON "ad_stats_daily" ("ad_id", "date");

CREATE INDEX "ad_stats_daily_date_idx"
ON "ad_stats_daily" ("date");

ALTER TABLE "ad_stats_daily"
ADD CONSTRAINT "ad_stats_daily_ad_id_fkey"
FOREIGN KEY ("ad_id")
REFERENCES "ads" ("id")
ON DELETE CASCADE;


-- ============================================================
-- SEO REDIRECTS
-- ============================================================

CREATE TABLE "redirects" (
  "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "from_path"   text    NOT NULL,
  "to_path"     text    NOT NULL,
  "status_code" integer NOT NULL DEFAULT 301,
  "created_at"  timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX "redirects_from_path_uidx"
ON "redirects" ("from_path");

ALTER TABLE "redirects"
ADD CONSTRAINT "redirects_status_code_check"
CHECK ("status_code" IN (301, 302, 307, 308));


-- ============================================================
-- FULL-TEXT SEARCH — TRIGGER
-- ============================================================

-- Function cập nhật search_vector khi article được insert/update
-- Dùng 'simple' dictionary để support tiếng Việt (không bị lỗi stemming)
-- unaccent giúp tìm kiếm không phân biệt dấu

CREATE OR REPLACE FUNCTION articles_search_vector_update()
RETURNS trigger AS $$
BEGIN
  NEW.search_vector :=
    setweight(to_tsvector('simple', unaccent(coalesce(NEW.title, ''))),   'A') ||
    setweight(to_tsvector('simple', unaccent(coalesce(NEW.summary, ''))), 'B');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "articles_search_vector_trigger"
BEFORE INSERT OR UPDATE ON "articles"
FOR EACH ROW EXECUTE FUNCTION articles_search_vector_update();


-- ============================================================
-- SEED — SITE SETTINGS (default row)
-- ============================================================

INSERT INTO "site_settings" ("id", "brand", "footer")
VALUES (
  1,
  '{"name": "", "logo_key": "", "favicon_key": ""}',
  '{"copyright": "", "links": []}'
)
ON CONFLICT ("id") DO NOTHING;


-- ============================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================

-- redirects: Middleware dùng anon client → cần policy SELECT public
-- Nếu không có policy này, middleware sẽ không đọc được redirect rules
ALTER TABLE "redirects" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "redirects_public_read"
ON "redirects"
FOR SELECT
USING (true);

-- Chỉ service role mới được INSERT/UPDATE/DELETE
CREATE POLICY "redirects_service_write"
ON "redirects"
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);


-- page_stats_daily: Chỉ service_role write (flush từ cron)
-- SELECT được phép để dashboard có thể đọc
ALTER TABLE "page_stats_daily" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "page_stats_public_read"
ON "page_stats_daily"
FOR SELECT
USING (true);

CREATE POLICY "page_stats_service_write"
ON "page_stats_daily"
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);


-- ==============================================
-- PERFORMANCE OPTIMIZATION INDEXES
-- ==============================================

-- 1. Index for articles sorting by created_at and deleted_at filter
CREATE INDEX IF NOT EXISTS "articles_deleted_created_idx" ON "articles" ("deleted_at", "created_at" DESC);

-- 2. Index for sorting by published_at (used in public feed and homepage listings)
CREATE INDEX IF NOT EXISTS "articles_published_at_desc_idx" ON "articles" ("published_at" DESC) WHERE ("status" = 'published' AND "deleted_at" IS NULL);

-- 3. Composite Index for category joins, status, and deletion filters
CREATE INDEX IF NOT EXISTS "articles_category_status_deleted_idx" ON "articles" ("category_id", "status", "deleted_at");

-- 4. Index for sorting ads by priority and active status
CREATE INDEX IF NOT EXISTS "ads_status_deleted_priority_idx" ON "ads" ("status", "priority" DESC) WHERE ("deleted_at" IS NULL);

-- 5. Index for sorting categories by priority
CREATE INDEX IF NOT EXISTS "categories_status_deleted_priority_idx" ON "categories" ("status", "priority" DESC) WHERE ("deleted_at" IS NULL);
